---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: configure debian apt repos
      copy:
        src: files/etc/sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        backup: yes
      when: ansible_distribution == "Debian"

    - name: update packages
      package:
        update_cache: yes

  tasks:
    # - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/media-codecs.yml
    - import_tasks: tasks/remove-games.yml
    - import_tasks: tasks/appearance.yml
    - import_tasks: tasks/zsh-confs.yml
    - import_tasks: tasks/add-flatpak.yml
    - import_tasks: tasks/add-motd.yml
