- hosts: localhost
  connection: local
  become: true

    - name: pre-run | update package cache
      tags: always
      package: update_cache=yes
      changed_when: False

  tasks:
    # - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/media-codecs.yml
    - import_tasks: tasks/remove-games.yml
    - import_tasks: tasks/desktop.yml
    - import_tasks: tasks/zsh-confs.yml