- name: gnome | appearance | dark theme
  tags: gnome,theme
  become_user: aelzagh
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: gnome | appearance | copy wallpaper file(fedora)
  tags: gnome,gnome-wallpaper
  copy:
    src: files/gnome/wallpapers/fedora-wallpaper.png
    dest: /usr/share/backgrounds/fedora-wallpaper.png
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Fedora"

- name: gnome | appearance | copy wallpaper file(debian)
  tags: gnome,gnome-wallpaper
  copy:
    src: files/gnome/wallpapers/debian-wallpaper.svg
    dest: /usr/share/backgrounds/debian-wallpaper.svg
    directory_mode:
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"

- name: gnome | appearance | set wallpaper(fedora)
  tags: gnome,gnome-wallpaper
  become_user: aelzagh
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/fedora-wallpaper.png'"
  when: ansible_distribution == "Fedora"

- name: gnome | appearance | set wallpaper(debian)
  tags: gnome,gnome-wallpaper
  become_user: aelzagh
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/debian-wallpaper.svg'"
  when: ansible_os_family == "Debian"

- name: gnome | appearance | set wallpaper position
  tags: gnome,gnome-wallpaper
  become_user: aelzagh
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"