- name: Copy from Local to Remote Target Machine with 'copy'
  copy:
    src: files/etc/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    backup: yes
  when: ansible_distribution = "Debian"

- name: refresh cache
  apt:
    update_cache: yes
  when: ansible_distribution = "Debian"
