- name: remove all games and its dependencies (debian)
  tags: gnome,gnome-apps
  apt:
    name:
      - gnome-2048
      - aisleriot
      - atomix
      - gnome-chess
      - five-or-more
      - hitori iagno
      - gnome-klotski
      - lightsoff
      - gnome-mahjongg
      - gnome-mines
      - gnome-nibbles
      - quadrapassel
      - four-in-a-row
      - gnome-robots
      - gnome-sudoku
      - swell-foop
      - tali
      - gnome-taquin
      - gnome-tetravex
    purge: true
    autoremove: true
    state: "absent"
  when: ansible_os_family == "Debian"