- name: installing zsh
  package:
    name: zsh

- name: change user shell to zsh
  become: yes
  user:
    name: aelzagh
    shell: /bin/zsh

- name: unarchive the configuration to user home
  unarchive:
    src: files/user-confs/myzsh.tar.gz
    dest: /home/aelzagh/
    owner: aelzagh
    group: aelzagh